name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup env vars for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "LALA=dev" >> $GITHUB_ENV
      - name: setup env vars for main
        if: github.event_name != 'pull_request'
        run: |
          echo "LALA=prod" >> $GITHUB_ENV
      - name: set env vars
        id: env-vars
        run: |
          echo "LELE=${{ env.LALA }}" >> $GITHUB_OUTPUT

      - name: print env vars
        run: |
          echo "${{ env.LALA }}"

      - name: print env output
        run: |
          echo "${{ steps.env-vars.outputs.LELE }}"
    outputs:
      LILI: ${{ steps.env-vars.outputs.LELE }}

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v2
      - name: print
        run: echo "${{ needs.setup.steps.env-vars.outputs.environment-name }}"
      - name: print 2
        run: echo "${{ needs.setup.env.LALA }}"
      - name: print 3
        run: echo "${{ needs.setup.env }}"
      - name: print 4
        run: echo "${{ env.LALA }}"
      - name: print output
        run: echo "${{ needs.setup.steps.outputs }}"
      - name: print output 1
        run: echo "${{ needs.setup.outputs.LILI }}"

      # - name: print 5
      #   run: echo "${{ LALA }}"
