name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup env vars for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "ENV=dev" >> $GITHUB_ENV
      - name: setup env vars for main
        if: github.event_name != 'pull_request'
        run: |
          echo "ENV=prod" >> $GITHUB_ENV
      - name: set env vars
        id: env-vars
        run: |
          echo "environment-name=${{ env.ENV }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v2
      - run: |
        echo "${{ needs.setup.steps.env-vars.outputs.environment-name }}"
        echo "${{ needs.setup.env.ENV }}"
